-- ==========================================================
-- BASELINE AMAN DB BARU (pnlxugnwevvepagzdxkr) - V1
-- Full schema + RLS + RPC + Storage. Pengganti V5:
--  * anon TAK BISA baca students/teachers/attendance/assessments/classes
--    langsung (V5: USING(true) = dump PII ke publik)
--  * RPC bulk dump (get_all_students_for_user) DIHAPUS
--  * Tak ada OLD/NEW di policy (invalid di RLS, V5 gagal push)
--  * profiles: self-update kolom non-sensitif saja, role/is_verified
--    hanya via RPC admin (anti eskalasi Guru->Admin)
--  * record_login_failure: hanya untuk identifier yang benar ada
--    (anti penguncian akun orang lain)
--  * stats RPC: tambah batch (app baca item['batch'])
--  * UNIQUE(student_id, date) utk upsert absensi onConflict
-- ==========================================================

-- ==========================================================
-- 1. TABEL
-- ==========================================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text,
  full_name text NOT NULL DEFAULT '',
  role text NOT NULL DEFAULT 'Guru',
  is_verified boolean NOT NULL DEFAULT false,
  phone text,
  address text,
  username text,
  onesignal_id text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.students (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nis text UNIQUE NOT NULL,
  name text NOT NULL DEFAULT '',
  gender text,
  birth_place text,
  birth_date text,
  religion text,
  address text,
  rt text,
  rw text,
  village text,
  class text,
  rombel text,
  batch text,
  curriculum text,
  school_of_origin text,
  status text NOT NULL DEFAULT 'Aktif',
  child_number int,
  father_name text,
  father_job text,
  father_phone text,
  mother_name text,
  mother_job text,
  mother_phone text,
  parent_phone text,
  parent_address text,
  parent_district text,
  parent_city text,
  parent_province text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.teachers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nip text,
  nik text,
  name text NOT NULL DEFAULT '',
  gender text,
  birth_place text,
  birth_date text,
  religion text,
  address text,
  last_education text,
  major text,
  university text,
  role text,
  subject text,
  start_date text,
  employment_status text,
  rank_grade text,
  npwp text,
  marital_status text,
  number_of_dependents int NOT NULL DEFAULT 0,
  phone text,
  email text,
  wali_kelas text,
  rombel_wali text,
  angkatan_wali text,
  status text NOT NULL DEFAULT 'Aktif',
  title_front text,
  title_back text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.classes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL DEFAULT '',
  rombel text,
  batch text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.attendance (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  date date NOT NULL,
  status text NOT NULL DEFAULT 'Alfa',
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (student_id, date)
);

CREATE TABLE IF NOT EXISTS public.assessments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id uuid NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  category text,
  score text,
  notes text,
  material text,
  image_url text,
  semester int NOT NULL DEFAULT 1,
  report_date timestamptz,
  is_published boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.school_data (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  npsn text,
  accreditation text,
  curriculum text,
  headmaster_name text,
  headmaster_nip text,
  email text,
  phone text,
  website text,
  address text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.documentation (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text,
  description text,
  image_url text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.login_attempts (
  identifier text PRIMARY KEY,
  failed_attempts integer NOT NULL DEFAULT 0,
  last_failed_at timestamptz DEFAULT now()
);

-- Index penjagaan query filter app (batch/class/rombel/status + join)
CREATE INDEX IF NOT EXISTS idx_students_class ON public.students (class, rombel, batch, status);
CREATE INDEX IF NOT EXISTS idx_attendance_lookup ON public.attendance (date, student_id);
CREATE INDEX IF NOT EXISTS idx_assessments_student ON public.assessments (student_id, semester);
CREATE INDEX IF NOT EXISTS idx_teachers_wali ON public.teachers (wali_kelas, rombel_wali, angkatan_wali);

-- ==========================================================
-- 2. HELPER ROLE (SECURITY DEFINER, terkunci)
-- ==========================================================
CREATE OR REPLACE FUNCTION public.is_staff()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM profiles WHERE id = (select auth.uid())
    AND role IN ('Admin', 'Guru', 'Super Admin'));
$$;
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM profiles WHERE id = (select auth.uid())
    AND role IN ('Admin', 'Super Admin'));
$$;
REVOKE ALL ON FUNCTION public.is_staff() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.is_admin() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_staff() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;

-- Trigger auto-create profiles (pengganti insert manual register.dart)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, role, is_verified)
  VALUES (NEW.id, NEW.email, COALESCE(NEW.raw_user_meta_data ->> 'full_name', ''), 'Guru', false)
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ==========================================================
-- 3. RLS ENABLE + GRANT DATA API
-- ==========================================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.school_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documentation ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.login_attempts ENABLE ROW LEVEL SECURITY;

-- Grant minimal supaya tabel terbaca PostgREST (otorisasi tetap via RLS)
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.students, public.teachers,
  public.classes, public.attendance, public.assessments,
  public.school_data, public.documentation TO authenticated;
GRANT SELECT ON public.school_data, public.documentation TO anon;
GRANT SELECT, INSERT ON public.profiles TO authenticated;
-- Self-update profil: kolom non-sensitif saja (role/is_verified/email TIDAK termasuk)
GRANT UPDATE (full_name, phone, address, username, onesignal_id) ON public.profiles TO authenticated;

-- ==========================================================
-- 4. POLICIES
-- ==========================================================
-- login_attempts: tanpa policy = tolak semua akses langsung (hanya via RPC)
DROP POLICY IF EXISTS "no_direct_access" ON public.login_attempts;
CREATE POLICY "no_direct_access" ON public.login_attempts
  FOR ALL TO public USING (false) WITH CHECK (false);

-- profiles: baca milik sendiri / staff; tulis sensitif HANYA via RPC admin
DROP POLICY IF EXISTS "profiles_select_own_or_staff" ON public.profiles;
CREATE POLICY "profiles_select_own_or_staff" ON public.profiles
  FOR SELECT TO authenticated
  USING ((select auth.uid()) = id OR public.is_staff());
DROP POLICY IF EXISTS "profiles_insert_own" ON public.profiles;
CREATE POLICY "profiles_insert_own" ON public.profiles
  FOR INSERT TO authenticated
  WITH CHECK ((select auth.uid()) = id AND role = 'Guru' AND is_verified IS FALSE);
DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
CREATE POLICY "profiles_update_own" ON public.profiles
  FOR UPDATE TO authenticated
  USING ((select auth.uid()) = id)
  WITH CHECK ((select auth.uid()) = id);
-- NOTE: tanpa policy DELETE/UPDATE staff di tabel -> pakai RPC verify/delete.

-- school_data + documentation: baca publik, tulis admin/staff
DROP POLICY IF EXISTS "school_data_public_read" ON public.school_data;
CREATE POLICY "school_data_public_read" ON public.school_data FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "school_data_admin_write" ON public.school_data;
CREATE POLICY "school_data_admin_write" ON public.school_data FOR INSERT TO authenticated WITH CHECK (public.is_admin());
DROP POLICY IF EXISTS "school_data_admin_upd" ON public.school_data;
CREATE POLICY "school_data_admin_upd" ON public.school_data FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
DROP POLICY IF EXISTS "school_data_admin_del" ON public.school_data;
CREATE POLICY "school_data_admin_del" ON public.school_data FOR DELETE TO authenticated USING (public.is_admin());

DROP POLICY IF EXISTS "documentation_public_read" ON public.documentation;
CREATE POLICY "documentation_public_read" ON public.documentation FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "documentation_staff_ins" ON public.documentation;
CREATE POLICY "documentation_staff_ins" ON public.documentation FOR INSERT TO authenticated WITH CHECK (public.is_staff());
DROP POLICY IF EXISTS "documentation_staff_upd" ON public.documentation;
CREATE POLICY "documentation_staff_upd" ON public.documentation FOR UPDATE TO authenticated USING (public.is_staff()) WITH CHECK (public.is_staff());
DROP POLICY IF EXISTS "documentation_staff_del" ON public.documentation;
CREATE POLICY "documentation_staff_del" ON public.documentation FOR DELETE TO authenticated USING (public.is_staff());

-- Data akademik: HANYA staff (anon lewat RPC scoped, bukan direct)
DROP POLICY IF EXISTS "students_staff_sel" ON public.students;
CREATE POLICY "students_staff_sel" ON public.students FOR SELECT TO authenticated USING (public.is_staff());
DROP POLICY IF EXISTS "students_staff_ins" ON public.students;
CREATE POLICY "students_staff_ins" ON public.students FOR INSERT TO authenticated WITH CHECK (public.is_staff());
DROP POLICY IF EXISTS "students_staff_upd" ON public.students;
CREATE POLICY "students_staff_upd" ON public.students FOR UPDATE TO authenticated USING (public.is_staff()) WITH CHECK (public.is_staff());
DROP POLICY IF EXISTS "students_staff_del" ON public.students;
CREATE POLICY "students_staff_del" ON public.students FOR DELETE TO authenticated USING (public.is_staff());

DROP POLICY IF EXISTS "teachers_staff_sel" ON public.teachers;
CREATE POLICY "teachers_staff_sel" ON public.teachers FOR SELECT TO authenticated USING (public.is_staff());
DROP POLICY IF EXISTS "teachers_staff_ins" ON public.teachers;
CREATE POLICY "teachers_staff_ins" ON public.teachers FOR INSERT TO authenticated WITH CHECK (public.is_staff());
DROP POLICY IF EXISTS "teachers_staff_upd" ON public.teachers;
CREATE POLICY "teachers_staff_upd" ON public.teachers FOR UPDATE TO authenticated USING (public.is_staff()) WITH CHECK (public.is_staff());
DROP POLICY IF EXISTS "teachers_staff_del" ON public.teachers;
CREATE POLICY "teachers_staff_del" ON public.teachers FOR DELETE TO authenticated USING (public.is_staff());

DROP POLICY IF EXISTS "classes_staff_sel" ON public.classes;
CREATE POLICY "classes_staff_sel" ON public.classes FOR SELECT TO authenticated USING (public.is_staff());
DROP POLICY IF EXISTS "classes_staff_ins" ON public.classes;
CREATE POLICY "classes_staff_ins" ON public.classes FOR INSERT TO authenticated WITH CHECK (public.is_staff());
DROP POLICY IF EXISTS "classes_staff_upd" ON public.classes;
CREATE POLICY "classes_staff_upd" ON public.classes FOR UPDATE TO authenticated USING (public.is_staff()) WITH CHECK (public.is_staff());
DROP POLICY IF EXISTS "classes_staff_del" ON public.classes;
CREATE POLICY "classes_staff_del" ON public.classes FOR DELETE TO authenticated USING (public.is_staff());

DROP POLICY IF EXISTS "attendance_staff_sel" ON public.attendance;
CREATE POLICY "attendance_staff_sel" ON public.attendance FOR SELECT TO authenticated USING (public.is_staff());
DROP POLICY IF EXISTS "attendance_staff_ins" ON public.attendance;
CREATE POLICY "attendance_staff_ins" ON public.attendance FOR INSERT TO authenticated WITH CHECK (public.is_staff());
DROP POLICY IF EXISTS "attendance_staff_upd" ON public.attendance;
CREATE POLICY "attendance_staff_upd" ON public.attendance FOR UPDATE TO authenticated USING (public.is_staff()) WITH CHECK (public.is_staff());
DROP POLICY IF EXISTS "attendance_staff_del" ON public.attendance;
CREATE POLICY "attendance_staff_del" ON public.attendance FOR DELETE TO authenticated USING (public.is_staff());

DROP POLICY IF EXISTS "assess_staff_sel" ON public.assessments;
CREATE POLICY "assess_staff_sel" ON public.assessments FOR SELECT TO authenticated USING (public.is_staff());
DROP POLICY IF EXISTS "assess_staff_ins" ON public.assessments;
CREATE POLICY "assess_staff_ins" ON public.assessments FOR INSERT TO authenticated WITH CHECK (public.is_staff());
DROP POLICY IF EXISTS "assess_staff_upd" ON public.assessments;
CREATE POLICY "assess_staff_upd" ON public.assessments FOR UPDATE TO authenticated USING (public.is_staff()) WITH CHECK (public.is_staff());
DROP POLICY IF EXISTS "assess_staff_del" ON public.assessments;
CREATE POLICY "assess_staff_del" ON public.assessments FOR DELETE TO authenticated USING (public.is_staff());

-- ==========================================================
-- 5. RPC (SECURITY DEFINER terkunci: revoke PUBLIC, grant minimal)
-- ==========================================================
-- Pre-login NIS: exact match 1 baris (rate-limit via login_attempts)
CREATE OR REPLACE FUNCTION public.get_student_auth(p_nis text)
RETURNS TABLE (nis text, name text, class text, batch text, rombel text)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
BEGIN
  RETURN QUERY SELECT s.nis, s.name, s.class, s.batch, s.rombel
    FROM students s WHERE s.nis = p_nis LIMIT 1;
END; $$;

CREATE OR REPLACE FUNCTION public.check_auth_blocked(p_identifier text)
RETURNS boolean LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
DECLARE attempts int;
BEGIN
  SELECT failed_attempts INTO attempts FROM login_attempts WHERE identifier = p_identifier;
  RETURN COALESCE(attempts, 0) >= 5;
END; $$;

-- Hanya catat gagal utk identifier yang benar ada (anti lock akun orang)
CREATE OR REPLACE FUNCTION public.record_login_failure(p_identifier text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE exists_flag boolean;
BEGIN
  SELECT EXISTS (SELECT 1 FROM students WHERE nis = p_identifier)
      OR EXISTS (SELECT 1 FROM auth.users WHERE email = p_identifier) INTO exists_flag;
  IF NOT exists_flag THEN RETURN; END IF;
  INSERT INTO login_attempts (identifier, failed_attempts, last_failed_at)
  VALUES (p_identifier, 1, now())
  ON CONFLICT (identifier) DO UPDATE
  SET failed_attempts = login_attempts.failed_attempts + 1, last_failed_at = now();
END; $$;

CREATE OR REPLACE FUNCTION public.reset_login_attempts(p_identifier text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  DELETE FROM login_attempts WHERE identifier = p_identifier;
END; $$;

-- Siswa: data sendiri by NIS (1 baris exact match)
CREATE OR REPLACE FUNCTION public.get_my_profile(p_nis text)
RETURNS SETOF students LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
BEGIN
  RETURN QUERY SELECT * FROM students WHERE nis = p_nis LIMIT 1;
END; $$;

CREATE OR REPLACE FUNCTION public.get_my_classmates(p_nis text)
RETURNS TABLE (id uuid, name text, nis text, class text, rombel text, batch text, status text)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
DECLARE v_class text;
BEGIN
  SELECT s.class INTO v_class FROM students s WHERE s.nis = p_nis LIMIT 1;
  IF v_class IS NULL THEN RETURN; END IF;
  RETURN QUERY SELECT s.id, s.name, s.nis, s.class, s.rombel, s.batch, s.status
    FROM students s WHERE s.class = v_class ORDER BY s.name;
END; $$;

-- Guru publik: kolom non-sensitif saja (tanpa nip/nik/phone/email)
CREATE OR REPLACE FUNCTION public.get_public_teachers()
RETURNS TABLE (id uuid, name text, role text, subject text, wali_kelas text, angkatan_wali text, rombel_wali text)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
BEGIN
  RETURN QUERY SELECT t.id, t.name, t.role, t.subject, t.wali_kelas, t.angkatan_wali, t.rombel_wali
    FROM teachers t ORDER BY t.name;
END; $$;

-- Rapor published milik sendiri (flat, utk adaptor app)
CREATE OR REPLACE FUNCTION public.get_my_rapor(p_nis text)
RETURNS TABLE (id bigint, student_id uuid, category text, score text, notes text,
  material text, image_url text, semester int, report_date timestamptz,
  is_published boolean, created_at timestamptz,
  student_name text, student_nis text, student_class text, student_rombel text, student_batch text)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
BEGIN
  RETURN QUERY SELECT a.id, a.student_id, a.category, a.score, a.notes,
    a.material, a.image_url, a.semester, a.report_date, a.is_published, a.created_at,
    s.name, s.nis, s.class, s.rombel, s.batch
    FROM assessments a JOIN students s ON s.id = a.student_id
    WHERE s.nis = p_nis AND a.is_published IS TRUE
    ORDER BY a.created_at DESC;
END; $$;

-- Absensi milik sendiri
CREATE OR REPLACE FUNCTION public.get_my_attendance(p_nis text)
RETURNS TABLE (date date, status text)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
BEGIN
  RETURN QUERY SELECT a.date, a.status FROM attendance a
    JOIN students s ON s.id = a.student_id
    WHERE s.nis = p_nis ORDER BY a.date DESC;
END; $$;

-- Stats agregat: staff saja (guard di dalam)
CREATE OR REPLACE FUNCTION public.get_student_stats_summary()
RETURNS TABLE (batch text, class_name text, total_count bigint, lulus_count bigint)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT public.is_staff() THEN RAISE EXCEPTION 'Akses ditolak'; END IF;
  RETURN QUERY SELECT s.batch, s.class, COUNT(*),
    COUNT(*) FILTER (WHERE s.status = 'Lulus')
    FROM students s GROUP BY s.batch, s.class;
END; $$;

-- Admin: verifikasi akun (pengganti update profiles langsung)
CREATE OR REPLACE FUNCTION public.verify_user_by_admin(p_user_id uuid, p_role text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION 'Akses ditolak: hanya Admin'; END IF;
  IF p_role NOT IN ('Guru', 'Admin') THEN RAISE EXCEPTION 'Role tidak valid'; END IF;
  UPDATE public.profiles SET is_verified = true, role = p_role WHERE id = p_user_id;
END; $$;

CREATE OR REPLACE FUNCTION public.delete_user_by_admin(target_user_id uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION 'Akses ditolak: hanya Admin'; END IF;
  DELETE FROM public.profiles WHERE id = target_user_id;
  DELETE FROM auth.users WHERE id = target_user_id;
END; $$;

-- RPC bulk dump lama: hapus (anon bisa sedot semua siswa)
DROP FUNCTION IF EXISTS public.get_all_students_for_user();

-- Kunci semua RPC: revoke PUBLIC, grant minimal
REVOKE ALL ON FUNCTION public.get_student_auth(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.check_auth_blocked(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.record_login_failure(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.reset_login_attempts(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_my_profile(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_my_classmates(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_public_teachers() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_my_rapor(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_my_attendance(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_student_stats_summary() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.verify_user_by_admin(uuid, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.delete_user_by_admin(uuid) FROM PUBLIC;

-- Pre-login + siswa tanpa sesi (scoped exact-NIS, bukan dump)
GRANT EXECUTE ON FUNCTION public.get_student_auth(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.check_auth_blocked(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_login_failure(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.reset_login_attempts(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_profile(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_classmates(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_public_teachers() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_rapor(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_attendance(text) TO anon, authenticated;
-- Staff & admin saja
GRANT EXECUTE ON FUNCTION public.get_student_stats_summary() TO authenticated;
GRANT EXECUTE ON FUNCTION public.verify_user_by_admin(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.delete_user_by_admin(uuid) TO authenticated;

-- ==========================================================
-- 6. STORAGE (bucket + RLS; upsert butuh INSERT+SELECT+UPDATE)
-- ==========================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('dokumentasi', 'dokumentasi', true), ('penilaian', 'penilaian', false)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "dokumentasi_public_read" ON storage.objects;
CREATE POLICY "dokumentasi_public_read" ON storage.objects
  FOR SELECT TO public USING (bucket_id = 'dokumentasi');
DROP POLICY IF EXISTS "dokumentasi_staff_ins" ON storage.objects;
CREATE POLICY "dokumentasi_staff_ins" ON storage.objects
  FOR INSERT TO authenticated WITH CHECK (bucket_id = 'dokumentasi' AND public.is_staff());
DROP POLICY IF EXISTS "dokumentasi_staff_sel" ON storage.objects;
CREATE POLICY "dokumentasi_staff_sel" ON storage.objects
  FOR SELECT TO authenticated USING (bucket_id = 'dokumentasi' AND public.is_staff());
DROP POLICY IF EXISTS "dokumentasi_staff_upd" ON storage.objects;
CREATE POLICY "dokumentasi_staff_upd" ON storage.objects
  FOR UPDATE TO authenticated
  USING (bucket_id = 'dokumentasi' AND public.is_staff())
  WITH CHECK (bucket_id = 'dokumentasi' AND public.is_staff());
DROP POLICY IF EXISTS "dokumentasi_staff_del" ON storage.objects;
CREATE POLICY "dokumentasi_staff_del" ON storage.objects
  FOR DELETE TO authenticated USING (bucket_id = 'dokumentasi' AND public.is_staff());

DROP POLICY IF EXISTS "penilaian_staff_all" ON storage.objects;
CREATE POLICY "penilaian_staff_all" ON storage.objects
  FOR ALL TO authenticated
  USING (bucket_id = 'penilaian' AND public.is_staff())
  WITH CHECK (bucket_id = 'penilaian' AND public.is_staff());

-- ==========================================================
-- 7. REALTIME (idempotent)
-- ==========================================================
DO $$ BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE
    public.profiles, public.students, public.teachers, public.classes,
    public.attendance, public.assessments, public.school_data, public.documentation;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
