-- ==========================================================
-- SELF-HOSTED POSTGRESQL MIGRATION
-- Tidak depend Supabase. Jalankan di PostgreSQL murni.
--
-- Cara pakai:
--   psql -U postgres -d nama_db -f self_hosted_migration.sql
--
-- App harus set session variable sebelum query:
--   SET app.current_user_id = '<uuid_user>';
-- ==========================================================

-- ==========================================================
-- 1. TABEL USERS (pengganti auth.users Supabase)
-- ==========================================================
CREATE TABLE IF NOT EXISTS public.users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text UNIQUE NOT NULL,
  password_hash text NOT NULL,
  full_name text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ==========================================================
-- 2. TABEL
-- ==========================================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
  email text,
  full_name text NOT NULL DEFAULT '',
  role text NOT NULL DEFAULT 'Guru',
  is_verified boolean NOT NULL DEFAULT false,
  phone text,
  address text,
  username text,
  onesignal_id text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.students (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nis text UNIQUE NOT NULL,
  name text NOT NULL DEFAULT '',
  gender text,
  birth_place text,
  birth_date text,
  religion text,
  address text,
  rt text,
  rw text,
  village text,
  class text,
  rombel text,
  batch text,
  curriculum text,
  school_of_origin text,
  status text NOT NULL DEFAULT 'Aktif',
  child_number int,
  father_name text,
  father_job text,
  father_phone text,
  mother_name text,
  mother_job text,
  mother_phone text,
  parent_phone text,
  parent_address text,
  parent_district text,
  parent_city text,
  parent_province text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.teachers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nip text,
  nik text,
  name text NOT NULL DEFAULT '',
  gender text,
  birth_place text,
  birth_date text,
  religion text,
  address text,
  last_education text,
  major text,
  university text,
  role text,
  subject text,
  start_date text,
  employment_status text,
  rank_grade text,
  npwp text,
  marital_status text,
  number_of_dependents int NOT NULL DEFAULT 0,
  phone text,
  email text,
  wali_kelas text,
  rombel_wali text,
  angkatan_wali text,
  status text NOT NULL DEFAULT 'Aktif',
  title_front text,
  title_back text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.classes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL DEFAULT '',
  rombel text,
  batch text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.attendance (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  date date NOT NULL,
  status text NOT NULL DEFAULT 'Alfa',
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (student_id, date)
);

CREATE TABLE IF NOT EXISTS public.assessments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id uuid NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  category text,
  score text,
  notes text,
  material text,
  image_url text,
  semester int NOT NULL DEFAULT 1,
  report_date timestamptz,
  is_published boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.school_data (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  npsn text,
  accreditation text,
  curriculum text,
  headmaster_name text,
  headmaster_nip text,
  email text,
  phone text,
  website text,
  address text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.documentation (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text,
  description text,
  image_url text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.login_attempts (
  identifier text PRIMARY KEY,
  failed_attempts integer NOT NULL DEFAULT 0,
  last_failed_at timestamptz DEFAULT now()
);

-- Index
CREATE INDEX IF NOT EXISTS idx_students_class ON public.students (class, rombel, batch, status);
CREATE INDEX IF NOT EXISTS idx_attendance_lookup ON public.attendance (date, student_id);
CREATE INDEX IF NOT EXISTS idx_assessments_student ON public.assessments (student_id, semester);
CREATE INDEX IF NOT EXISTS idx_teachers_wali ON public.teachers (wali_kelas, rombel_wali, angkatan_wali);

-- ==========================================================
-- 3. HELPER: get current user id dari session variable
-- ==========================================================
-- App harus SET app.current_user_id = '<uuid>' sebelum query.
-- Contoh: SET app.current_user_id = '11111111-1111-1111-1111-111111111111';

CREATE OR REPLACE FUNCTION public.current_user_id()
RETURNS uuid LANGUAGE sql STABLE AS $$
  SELECT current_setting('app.current_user_id', true)::uuid;
$$;

CREATE OR REPLACE FUNCTION public.is_staff()
RETURNS boolean LANGUAGE sql STABLE AS $$
  SELECT EXISTS (
    SELECT 1 FROM profiles
    WHERE id = public.current_user_id()
      AND role IN ('Admin', 'Guru', 'Super Admin')
  );
$$;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean LANGUAGE sql STABLE AS $$
  SELECT EXISTS (
    SELECT 1 FROM profiles
    WHERE id = public.current_user_id()
      AND role IN ('Admin', 'Super Admin')
  );
$$;

-- Trigger auto-create profiles saat insert users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, role, is_verified)
  VALUES (NEW.id, NEW.email, NEW.full_name, 'Guru', false)
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_user_created ON public.users;
CREATE TRIGGER on_user_created AFTER INSERT ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ==========================================================
-- 4. RLS ENABLE
-- ==========================================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.school_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documentation ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.login_attempts ENABLE ROW LEVEL SECURITY;

-- ==========================================================
-- 5. POLICIES
-- ==========================================================
-- login_attempts: tolak semua akses langsung (hanya via RPC)
DROP POLICY IF EXISTS "no_direct_access" ON public.login_attempts;
CREATE POLICY "no_direct_access" ON public.login_attempts
  FOR ALL USING (false) WITH CHECK (false);

-- profiles
DROP POLICY IF EXISTS "profiles_select_own_or_staff" ON public.profiles;
CREATE POLICY "profiles_select_own_or_staff" ON public.profiles
  FOR SELECT USING (public.current_user_id() = id OR public.is_staff());

DROP POLICY IF EXISTS "profiles_insert_own" ON public.profiles;
CREATE POLICY "profiles_insert_own" ON public.profiles
  FOR INSERT
  WITH CHECK (public.current_user_id() = id AND role = 'Guru' AND is_verified IS FALSE);

DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
CREATE POLICY "profiles_update_own" ON public.profiles
  FOR UPDATE
  USING (public.current_user_id() = id)
  WITH CHECK (public.current_user_id() = id);

-- school_data: baca publik, tulis admin
DROP POLICY IF EXISTS "school_data_public_read" ON public.school_data;
CREATE POLICY "school_data_public_read" ON public.school_data FOR SELECT USING (true);
DROP POLICY IF EXISTS "school_data_admin_write" ON public.school_data;
CREATE POLICY "school_data_admin_write" ON public.school_data FOR INSERT WITH CHECK (public.is_admin());
DROP POLICY IF EXISTS "school_data_admin_upd" ON public.school_data;
CREATE POLICY "school_data_admin_upd" ON public.school_data FOR UPDATE USING (public.is_admin()) WITH CHECK (public.is_admin());
DROP POLICY IF EXISTS "school_data_admin_del" ON public.school_data;
CREATE POLICY "school_data_admin_del" ON public.school_data FOR DELETE USING (public.is_admin());

-- documentation: baca publik, tulis staff
DROP POLICY IF EXISTS "documentation_public_read" ON public.documentation;
CREATE POLICY "documentation_public_read" ON public.documentation FOR SELECT USING (true);
DROP POLICY IF EXISTS "documentation_staff_ins" ON public.documentation;
CREATE POLICY "documentation_staff_ins" ON public.documentation FOR INSERT WITH CHECK (public.is_staff());
DROP POLICY IF EXISTS "documentation_staff_upd" ON public.documentation;
CREATE POLICY "documentation_staff_upd" ON public.documentation FOR UPDATE USING (public.is_staff()) WITH CHECK (public.is_staff());
DROP POLICY IF EXISTS "documentation_staff_del" ON public.documentation;
CREATE POLICY "documentation_staff_del" ON public.documentation FOR DELETE USING (public.is_staff());

-- students: staff only
DROP POLICY IF EXISTS "students_staff_sel" ON public.students;
CREATE POLICY "students_staff_sel" ON public.students FOR SELECT USING (public.is_staff());
DROP POLICY IF EXISTS "students_staff_ins" ON public.students;
CREATE POLICY "students_staff_ins" ON public.students FOR INSERT WITH CHECK (public.is_staff());
DROP POLICY IF EXISTS "students_staff_upd" ON public.students;
CREATE POLICY "students_staff_upd" ON public.students FOR UPDATE USING (public.is_staff()) WITH CHECK (public.is_staff());
DROP POLICY IF EXISTS "students_staff_del" ON public.students;
CREATE POLICY "students_staff_del" ON public.students FOR DELETE USING (public.is_staff());

-- teachers: staff only
DROP POLICY IF EXISTS "teachers_staff_sel" ON public.teachers;
CREATE POLICY "teachers_staff_sel" ON public.teachers FOR SELECT USING (public.is_staff());
DROP POLICY IF EXISTS "teachers_staff_ins" ON public.teachers;
CREATE POLICY "teachers_staff_ins" ON public.teachers FOR INSERT WITH CHECK (public.is_staff());
DROP POLICY IF EXISTS "teachers_staff_upd" ON public.teachers;
CREATE POLICY "teachers_staff_upd" ON public.teachers FOR UPDATE USING (public.is_staff()) WITH CHECK (public.is_staff());
DROP POLICY IF EXISTS "teachers_staff_del" ON public.teachers;
CREATE POLICY "teachers_staff_del" ON public.teachers FOR DELETE USING (public.is_staff());

-- classes: staff only
DROP POLICY IF EXISTS "classes_staff_sel" ON public.classes;
CREATE POLICY "classes_staff_sel" ON public.classes FOR SELECT USING (public.is_staff());
DROP POLICY IF EXISTS "classes_staff_ins" ON public.classes;
CREATE POLICY "classes_staff_ins" ON public.classes FOR INSERT WITH CHECK (public.is_staff());
DROP POLICY IF EXISTS "classes_staff_upd" ON public.classes;
CREATE POLICY "classes_staff_upd" ON public.classes FOR UPDATE USING (public.is_staff()) WITH CHECK (public.is_staff());
DROP POLICY IF EXISTS "classes_staff_del" ON public.classes;
CREATE POLICY "classes_staff_del" ON public.classes FOR DELETE USING (public.is_staff());

-- attendance: staff only
DROP POLICY IF EXISTS "attendance_staff_sel" ON public.attendance;
CREATE POLICY "attendance_staff_sel" ON public.attendance FOR SELECT USING (public.is_staff());
DROP POLICY IF EXISTS "attendance_staff_ins" ON public.attendance;
CREATE POLICY "attendance_staff_ins" ON public.attendance FOR INSERT WITH CHECK (public.is_staff());
DROP POLICY IF EXISTS "attendance_staff_upd" ON public.attendance;
CREATE POLICY "attendance_staff_upd" ON public.attendance FOR UPDATE USING (public.is_staff()) WITH CHECK (public.is_staff());
DROP POLICY IF EXISTS "attendance_staff_del" ON public.attendance;
CREATE POLICY "attendance_staff_del" ON public.attendance FOR DELETE USING (public.is_staff());

-- assessments: staff only
DROP POLICY IF EXISTS "assess_staff_sel" ON public.assessments;
CREATE POLICY "assess_staff_sel" ON public.assessments FOR SELECT USING (public.is_staff());
DROP POLICY IF EXISTS "assess_staff_ins" ON public.assessments;
CREATE POLICY "assess_staff_ins" ON public.assessments FOR INSERT WITH CHECK (public.is_staff());
DROP POLICY IF EXISTS "assess_staff_upd" ON public.assessments;
CREATE POLICY "assess_staff_upd" ON public.assessments FOR UPDATE USING (public.is_staff()) WITH CHECK (public.is_staff());
DROP POLICY IF EXISTS "assess_staff_del" ON public.assessments;
CREATE POLICY "assess_staff_del" ON public.assessments FOR DELETE USING (public.is_staff());

-- ==========================================================
-- 6. FUNCTIONS (RPC)
-- ==========================================================
CREATE OR REPLACE FUNCTION public.get_student_auth(p_nis text)
RETURNS TABLE (nis text, name text, class text, batch text, rombel text)
LANGUAGE plpgsql STABLE AS $$
BEGIN
  RETURN QUERY SELECT s.nis, s.name, s.class, s.batch, s.rombel
    FROM students s WHERE s.nis = p_nis LIMIT 1;
END; $$;

CREATE OR REPLACE FUNCTION public.check_auth_blocked(p_identifier text)
RETURNS boolean LANGUAGE plpgsql STABLE AS $$
DECLARE attempts int;
BEGIN
  SELECT failed_attempts INTO attempts FROM login_attempts WHERE identifier = p_identifier;
  RETURN COALESCE(attempts, 0) >= 5;
END; $$;

CREATE OR REPLACE FUNCTION public.record_login_failure(p_identifier text)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE exists_flag boolean;
BEGIN
  SELECT EXISTS (SELECT 1 FROM students WHERE nis = p_identifier)
      OR EXISTS (SELECT 1 FROM users WHERE email = p_identifier) INTO exists_flag;
  IF NOT exists_flag THEN RETURN; END IF;
  INSERT INTO login_attempts (identifier, failed_attempts, last_failed_at)
  VALUES (p_identifier, 1, now())
  ON CONFLICT (identifier) DO UPDATE
  SET failed_attempts = login_attempts.failed_attempts + 1, last_failed_at = now();
END; $$;

CREATE OR REPLACE FUNCTION public.reset_login_attempts(p_identifier text)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  DELETE FROM login_attempts WHERE identifier = p_identifier;
END; $$;

CREATE OR REPLACE FUNCTION public.get_my_profile(p_nis text)
RETURNS SETOF students LANGUAGE plpgsql STABLE AS $$
BEGIN
  RETURN QUERY SELECT * FROM students WHERE nis = p_nis LIMIT 1;
END; $$;

CREATE OR REPLACE FUNCTION public.get_my_classmates(p_nis text)
RETURNS TABLE (id uuid, name text, nis text, class text, rombel text, batch text, status text)
LANGUAGE plpgsql STABLE AS $$
DECLARE v_class text;
BEGIN
  SELECT s.class INTO v_class FROM students s WHERE s.nis = p_nis LIMIT 1;
  IF v_class IS NULL THEN RETURN; END IF;
  RETURN QUERY SELECT s.id, s.name, s.nis, s.class, s.rombel, s.batch, s.status
    FROM students s WHERE s.class = v_class ORDER BY s.name;
END; $$;

CREATE OR REPLACE FUNCTION public.get_public_teachers()
RETURNS TABLE (id uuid, name text, role text, subject text, wali_kelas text, angkatan_wali text, rombel_wali text)
LANGUAGE plpgsql STABLE AS $$
BEGIN
  RETURN QUERY SELECT t.id, t.name, t.role, t.subject, t.wali_kelas, t.angkatan_wali, t.rombel_wali
    FROM teachers t ORDER BY t.name;
END; $$;

CREATE OR REPLACE FUNCTION public.get_my_rapor(p_nis text)
RETURNS TABLE (id bigint, student_id uuid, category text, score text, notes text,
  material text, image_url text, semester int, report_date timestamptz,
  is_published boolean, created_at timestamptz,
  student_name text, student_nis text, student_class text, student_rombel text, student_batch text)
LANGUAGE plpgsql STABLE AS $$
BEGIN
  RETURN QUERY SELECT a.id, a.student_id, a.category, a.score, a.notes,
    a.material, a.image_url, a.semester, a.report_date, a.is_published, a.created_at,
    s.name, s.nis, s.class, s.rombel, s.batch
    FROM assessments a JOIN students s ON s.id = a.student_id
    WHERE s.nis = p_nis AND a.is_published IS TRUE
    ORDER BY a.created_at DESC;
END; $$;

CREATE OR REPLACE FUNCTION public.get_my_attendance(p_nis text)
RETURNS TABLE (date date, status text)
LANGUAGE plpgsql STABLE AS $$
BEGIN
  RETURN QUERY SELECT a.date, a.status FROM attendance a
    JOIN students s ON s.id = a.student_id
    WHERE s.nis = p_nis ORDER BY a.date DESC;
END; $$;

CREATE OR REPLACE FUNCTION public.get_student_stats_summary()
RETURNS TABLE (batch text, class_name text, total_count bigint, lulus_count bigint)
LANGUAGE plpgsql STABLE AS $$
BEGIN
  IF NOT public.is_staff() THEN RAISE EXCEPTION 'Akses ditolak'; END IF;
  RETURN QUERY SELECT s.batch, s.class, COUNT(*),
    COUNT(*) FILTER (WHERE s.status = 'Lulus')
    FROM students s GROUP BY s.batch, s.class;
END; $$;

CREATE OR REPLACE FUNCTION public.verify_user_by_admin(p_user_id uuid, p_role text)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION 'Akses ditolak: hanya Admin'; END IF;
  IF p_role NOT IN ('Guru', 'Admin') THEN RAISE EXCEPTION 'Role tidak valid'; END IF;
  UPDATE public.profiles SET is_verified = true, role = p_role WHERE id = p_user_id;
END; $$;

CREATE OR REPLACE FUNCTION public.delete_user_by_admin(target_user_id uuid)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION 'Akses ditolak: hanya Admin'; END IF;
  DELETE FROM public.profiles WHERE id = target_user_id;
  DELETE FROM public.users WHERE id = target_user_id;
END; $$;

-- ==========================================================
-- 7. SEED DATA (demo)
-- ==========================================================
-- Password default: 'password123' ( bcrypt hash, ganti di production )
-- hash ini untuk password: password123
INSERT INTO public.users (id, email, password_hash, full_name)
VALUES
  ('11111111-1111-1111-1111-111111111111', 'admin@sekolah.id',
   '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Admin Utama'),
  ('22222222-2222-2222-2222-222222222222', 'guru@sekolah.id',
   '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Guru Demo')
ON CONFLICT (id) DO NOTHING;

-- Set role admin untuk user pertama
UPDATE public.profiles SET role = 'Admin', is_verified = true
WHERE id = '11111111-1111-1111-1111-111111111111';

INSERT INTO public.school_data
  (name, npsn, accreditation, curriculum, headmaster_name, headmaster_nip, email, phone, address)
SELECT 'TK Pelita Bangsa', '12345678', 'A', 'Merdeka',
  'Siti Rahayu', '196501011990032001',
  'info@tkpelita.sch.id', '081234567890', 'Jl. Pendidikan No. 1'
WHERE NOT EXISTS (SELECT 1 FROM public.school_data);

INSERT INTO public.classes (name, rombel, batch)
SELECT 'TKA', 'A', '2024'
WHERE NOT EXISTS (SELECT 1 FROM public.classes WHERE name = 'TKA' AND rombel = 'A');
INSERT INTO public.classes (name, rombel, batch)
SELECT 'TKB', 'A', '2024'
WHERE NOT EXISTS (SELECT 1 FROM public.classes WHERE name = 'TKB' AND rombel = 'A');

INSERT INTO public.teachers
  (name, nip, gender, role, subject, wali_kelas, rombel_wali, angkatan_wali, status)
SELECT 'Siti Rahayu', '196501011990032001', 'Perempuan',
  'Wali Kelas', 'Tematik', 'TKA', 'A', '2024', 'Aktif'
WHERE NOT EXISTS (SELECT 1 FROM public.teachers WHERE nip = '196501011990032001');
INSERT INTO public.teachers (name, nip, gender, role, subject, status)
SELECT 'Budi Hartono', '197803152005011002', 'Laki-laki',
  'Guru Mapel', 'Agama', 'Aktif'
WHERE NOT EXISTS (SELECT 1 FROM public.teachers WHERE nip = '197803152005011002');

INSERT INTO public.students
  (id, nis, name, gender, class, rombel, batch, curriculum, status,
   father_name, mother_name, parent_phone)
VALUES
  ('aaaaaaa1-aaaa-aaaa-aaaa-aaaaaaaaaaa1', '1001', 'Ahmad Fauzi', 'Laki-laki',
   'TKA', 'A', '2024', 'Merdeka', 'Aktif',
   'Joko Susilo', 'Dewi Lestari', '081111111111'),
  ('aaaaaaa2-aaaa-aaaa-aaaa-aaaaaaaaaaa2', '1002', 'Aisyah Putri', 'Perempuan',
   'TKA', 'A', '2024', 'Merdeka', 'Aktif',
   'Agus Wijaya', 'Rina Marlina', '082222222222')
ON CONFLICT (nis) DO NOTHING;

INSERT INTO public.attendance (student_id, date, status)
SELECT 'aaaaaaa1-aaaa-aaaa-aaaa-aaaaaaaaaaa1', CURRENT_DATE, 'Hadir'
WHERE NOT EXISTS (
  SELECT 1 FROM public.attendance
  WHERE student_id = 'aaaaaaa1-aaaa-aaaa-aaaa-aaaaaaaaaaa1' AND date = CURRENT_DATE);
INSERT INTO public.attendance (student_id, date, status)
SELECT 'aaaaaaa2-aaaa-aaaa-aaaa-aaaaaaaaaaa2', CURRENT_DATE, 'Sakit'
WHERE NOT EXISTS (
  SELECT 1 FROM public.attendance
  WHERE student_id = 'aaaaaaa2-aaaa-aaaa-aaaa-aaaaaaaaaaa2' AND date = CURRENT_DATE);

INSERT INTO public.assessments
  (student_id, category, score, notes, material, semester, report_date, is_published)
SELECT 'aaaaaaa1-aaaa-aaaa-aaaa-aaaaaaaaaaa1', c.category, 'Berkembang Baik',
  'Anak menunjukkan perkembangan baik pada ' || c.category,
  'Materi semester 1', 1, now(), true
FROM (VALUES
  ('Nilai Agama dan Budi Pekerti'),
  ('Jati Diri'),
  ('Dasar Literasi, Sains, Teknologi, Rekayasa, & Seni')
) AS c(category)
WHERE NOT EXISTS (
  SELECT 1 FROM public.assessments a
  WHERE a.student_id = 'aaaaaaa1-aaaa-aaaa-aaaa-aaaaaaaaaaa1'
    AND a.category = c.category AND a.semester = 1);

INSERT INTO public.documentation (title, description)
SELECT 'Kegiatan Belajar Semester 1', 'Dokumentasi kegiatan belajar mengajar semester 1'
WHERE NOT EXISTS (SELECT 1 FROM public.documentation);

-- ==========================================================
-- DONE.
-- 10 tabel (users + 9 data), 12 functions, seed data.
--
-- Contoh penggunaan dari app:
--   BEGIN;
--   SET LOCAL app.current_user_id = '11111111-1111-1111-1111-111111111111';
--   SELECT * FROM students;  -- RLS aktif
--   COMMIT;
-- ==========================================================
